### ISSUE TITLE
请问平均一次请求需要多少时间？

### ISSUE THREAD

**Issue by dd-rongfa** [geekr-dev/openai-proxy#1]
我测试云服务器通过api访问，从发送请求到收到请求大概需要20+秒。
model gpt-3.5-turbo
prompt 就一句话。

**Comment by geekr-dev** [comment]
要看语义分析的复杂性 有的时候几个字但是很模糊也需要很长时间 应该是越明确越好 我看我这边后台统计平均响应时间是6s多

**Comment by fabrietech** [comment]
streaming 模式, 吐第一个字大概需要多久

**Comment by dd-rongfa** [comment]
现在搞明白了，是由于使用的是非streaming模式，答案输出完才回传的，导致很慢。
